SET IDENTITY_INSERT dbo.SubArea ON
GO

insert into dbo.SubArea (Id,Nombre,Referente,Area_id)

values

(1,'SIN SUB-AREA','SIN REFERENTE',1),
(2,'Limpieza','',3),
(3,'Dto. de Registro - Antecedentes Historicos / Busqueda de Origenes','Maria Isabel Mazzocchetti',8),
(4,'Conmutador','',3),
(5,'Recepción','',3),
(6,'Atención al publico','',4),
(7,'Mesa General de Entradas, Salidas y Archivo','',8),
(8,'Conciliaciones Bancarias','Lic. Silvia Cortes',2),
(9,'Dto. de Tesorería - Coordinación','Alejandra Galán',2),
(10,'Dto. de Tesorería - Pagos','Norma Lopez / Maria Vicetto',2),
(11,'Dto. de Tesorería - Caja','Fernando Dominguez',2),
(12,'Dto. de Tesorería - Fax','',2),
(13,'Dto. de Tesorería','',2),
(14,'Dto. de Registro - Antecedentes / Apertura de Legajos','Maria Isabel Mazzocchetti',8),
(15,'Dto. de Registro - Archivos / Movimientos de legajos','Maria Isabel Mazzocchetti',8),
(16,'Atención al Trabajador/a - Coordinación','Dr. Adolfo Panelo',8),
(17,'Atención al Trabajador/a','',8),
(18,'Seguridad e Higiene','Arq. Marcelo Alvariñas',3),
(19,'Guardia Choferes ','',3),
(20,'Guardia  Policial','Arq. Gustavo Piergacomi',3),
(21,'Subs. Nac. de Derechos - Subsecretario','Lic. Roberto Candiano',5),
(22,'Subs. Nac. de Derechos - Secretaría Privada','Carlos Garay',5),
(23,'Subs. Nac. de Derechos - Compras','Julian Iglesias',5),
(24,'Subs. Nac. de Derechos - Jefatura de Asesores','Alicia Cusinato',5),
(25,'Subs. Nac. de Derechos - Coordinación','Andrea Benítez',5),
(26,'Subs. Nac. de Derechos - Despacho','Gabriela Da Costa',5),
(27,'Subs. Nac. de Derechos - Anexo Despacho','Zulma Gonzalez / Roberto Troncoso',5),
(28,'Dir. Nac. de Sist. de Protección de Derechos - Dirección','Lic. Carolina Ríos',6),
(29,'Dir. Nac. de Sist. de Protección de Derechos - Despacho','',6),
(30,'Dir. Nac. de Gestión y Desarrollo Institucional - Equipo Tecnico','Guillermo Badino',7),
(31,'Monitoreo','Lic. Mónica Ranero',8),
(32,'P.A.E. (Ex Línea de Atención) - Coordinación','Lic. Patricia Alonso / Lic. Analia G. Cabriada',4),
(33,'P.A.E. (Ex Linea de Atención) - Mesa de Entradas','Patricia Reyes',4),
(34,'P.A.E. (Ex Linea de Atención) - Asistenciales','',4),
(35,'Linea de Inclusion a una Familia Adoptiva','Dr. Hertor Vito',4),
(36,'D.N.P.P.I. - Equipo Tecnico','',4),
(37,'Programa de Prev y Errad. Del Trabajo Infantil','Mirentxu Baca',4),
(38,'Refugiados','Maria Susana Guasti',4),
(39,'Conductas Saludables','',4),
(40,'Prog. Niños con Madres Privadas de la Libertad / Buen Trato','Lic. Catalina Hvidbo',4),
(41,'Prestaciones Positivas','Lic. Viviana  Segal',4),
(42,'PPMI (Violencia Familiar)','',4),
(43,'Observatorio Federal','',4),
(44,'Articulación Territorial','',4),
(45,'Comunicaciones','',13),
(46,'A.G.N.','',8),
(47,'A.T.E.','',8),
(48,'Dir. Nac. de Promoción y Protección Integral - Dirección','Arnoldo A. Scherrer Vivas',4),
(49,'D.N.P.P.I. - Secretaria Privada','Ester Cabral',4),
(50,'D.N.P.P.I. - Despacho','',4),
(51,'D.N.P.P.I. - Convenios',' Walter Burgos',4),
(52,'D.N.P.P.I. - Línea de Crianza','Dra. Laura Buzeta',4),
(53,'D.N.P.P.I. - Equipo Técnico','',4),
(54,'Trata -  Vulneración de los Derechos - Coordinación','Lic. Patricia Sanchez',4),
(55,'Trata -  Vulneración de los Derechos','',4),
(56,'D.I.N.A.I. - Dirección','',9),
(57,'D.I.N.A.I. - Secretaria','Rosana Aboy / Jessica Quintieri',9),
(58,'D.I.N.A.I. - Jurídica','',9),
(59,'D.I.N.A.I. - Área Contable, Despacho','',9),
(60,'D.I.N.A.I. - RR.HH.','',9),
(61,'D.I.N.A.I. - Área Federal','',9),
(62,'D.I.N.A.I. - Seguridad','',9),
(63,'Identidad - Búsqueda de Orígenes','Natalia Caeiro',8),
(64,'Protagonismo Adolescente','Lic. Daniela Carro',8),
(65,'Territorio en Movimiento','Prof. Ángela Viviana Balmaceda',8),
(66,'Unidad de Auditoria Interna - Dirección',' Dr. Félix G. Bialet',8),
(67,'Unidad de Auditoria Interna ','',8),
(68,'Servicios Generales ','Ignacio Rivero',3),
(69,'Prestaciones','Ana Cambareri',8),
(70,'Cocina 2do','Leonor',3),
(71,'D.I.N.A.P.A.M. - Dirección','Mg. Susana Rubinstein',10),
(72,'D.I.N.A.P.A.M. - Secretaria Privada','',10),
(73,'D.I.N.A.P.A.M. - Mesa de Entradas','',10),
(74,'D.I.N.A.P.A.M. - Monitoreo','',10),
(75,'D.I.N.A.P.A.M. - Coordinadores','',10),
(76,'D.I.N.A.P.A.M. - Despacho','',10),
(77,'D.I.N.A.P.A.M. - Ecos','',10),
(78,'D.I.N.A.P.A.M. - Hogares','',10),
(79,'D.I.N.A.P.A.M. - Cuidados','',10),
(80,'D.I.N.A.P.A.M. - Reg. Nac. de Cuidadores Domiciliarios','',10),
(81,'RR.HH. - Dirección','Dr. Sergio Aromi ',11),
(82,'RR.HH. - Mesa De Entradas','',11),
(83,'RR.HH. - Asistencia','Adriana Fernández',11),
(84,'RR.HH. - Carrera Administrativa','Liliana Gette',11),
(85,'RR.HH. - Capacitación ','Lic. Natalia Hirschfeld',11),
(86,'RR.HH. - Legajos','',11),
(87,'RR.HH. - Contratos ','Lic. Marcos Coronel',11),
(88,'RR.HH. - Despacho y Notificaciones','Noelia Balaki',11),
(89,'RR.HH. - Seguros y ART','',11),
(90,'RR.HH. - Coordinación Técnica Evaluadora','',11),
(91,'Dir. de Asuntos Legales - Dirección','Dra. Alejandra Escolar',12),
(92,'Dir. de Asuntos Legales - Dictámenes','',12),
(93,'Dir. de Asuntos Legales - Asistencia Jurídica','',12),
(94,'Dir. de Asuntos Legales - Actuación Judicial','',12),
(95,'Dir. de Asuntos Legales - Mesa de Entradas','',12),
(96,'Dir. de Asuntos Legales - Sumarios','',12),
(97,'Dir. de Asuntos Legales - Biblioteca','',12),
(98,'Sec. Nac. de Niñez y Adolescencia y Flia - Secretario','Lic. Gabriel Enrique Castelli',8),
(99,'S.E.N.N.A.F. - Secretaría Privada','Mariana Illescas - Sofia Schild',8),
(100,'Sala de Situación','',8),
(101,'Jefatura de Gabinete - Coordinación','Mario Lozada',13),
(102,'Jefatura de Gabinete - Despacho','Adriana Farace',13),
(103,'Jefatura de Gabinete','',13),
(104,'Jefatura de Gabinete - RR.HH.','Javier Zavalia',13),
(105,'Jefatura de Gabinete - Inmuebles','Martín Vivot',13),
(106,'Jefatura de Gabinete - Plan Enia','',13),
(107,'Subs. de Desarrollo Instituc. e Integrac. Federal - Subsecretaria','Dra. Mercedes Agresti',14),
(108,'Subs. de Desarrollo Instituc. e Integrac. Federal - Secretaría Privada','',14),
(109,'Subs. de Desarrollo Instituc. e Integrac. Federal - Despacho','',14),
(110,'Subs. de Desarrollo Instituc. e Integrac. Federal - Consejo Federal','',14),
(111,'Subs. de Desarrollo Instituc. e Integrac. Federal - Área Contable','',14),
(112,'Subs. de Desarrollo Instituc. e Integrac. Federal - Viáticos','',14),
(113,'Unidad de Despacho - Coordinación','Dr. Silvia Karina Blanco',8),
(114,'Unidad de Despacho - Mesa de Entrada','',8),
(115,'Unidad de Despacho - Protocolizacion','',8),
(116,'Unidad de Despacho - Control','',8),
(117,'Relaciones Internacionales Prensa','Lic. Alejo Torres De La Puerta',8),
(118,'Dir. Nac. de Gestión y Desarrollo Institucional - Dirección','Guillermo Badino',7),
(119,'Dir. Nac. de Gestión y Desarrollo Institucional - Secretaría Privada','',7),
(120,'Transferencia de Tecnología Social','',8),
(121,'Comisión de Recepción Definitiva','Cont. Ignacio Flores',8),
(122,'Cocina 4to','',3),
(123,'D.T.A. - Dirección','Cdor. Raúl F. Laballos',2),
(124,'D.T.A. - Secretaría Privada','Iván Carrasco',2),
(125,'D.T.A. - Asesores','',2),
(126,'Mesa de Entradas de DTA','Rosa Cáceres',2),
(127,'Informática - Coordinación','Sebastián Tsiros',2),
(128,'Informática - Administración','Barbara Bogado',2),
(129,'Informática - Mesa de Ayuda ','Graciela Manghera / Natalia Ortíz',2),
(130,'Informática - Técnica ','Horacio Feijó / Federico Balbuena',2),
(131,'Informática - Administración de Servidores / GDE','Pablo Martinovic',2),
(132,'Informática - Desarrollo de Sistemas','',2),
(133,'Dir. de Programación y Control Presupuestario','Patricia Urquiza',2),
(134,'Dir. de Programación Financiera','Gustavo Buckley',2),
(135,'Dpto. de Contabilidad','Marcela Silva',2),
(136,'Dpto. de Contabilidad - Liquidación de Cuentas','',2),
(137,'Dpto. de Presupuesto','Gladis Urquiza',2),
(138,'Rendición de Cuentas / Viáticos','',2),
(139,'Infra.. Edilicia, Patrimonio, Contrat. Y Suminis. - Coordinación','Martin Vayo',2),
(140,'Infraestructura Edilicia - Coordinación','Arq. Gustavo Piergiacomi',2),
(141,'Infraestructura Edilicia - Mesa de Entradas','',2),
(142,'Infraestructura Edilicia - Equipo Tecnico','',2),
(143,'Dpto. de Patrimonio','Romina Gauna',2),
(144,'Dpto. de Patrimonio - Archivo','Gabriela Joaquín',2),
(145,'Dpto. de Compras - Coordinación Contratac. y Suminis.','',2),
(146,'Dpto. de Compras - Contrataciones','',2),
(147,'Dpto. de Compras - Comisión Evaluadora','',2),
(148,'Liquidación de Sueldos y Haberes','Ana María García',2),
(149,'U.P.C.N.','Sec. Gral. Edgardo Stiefkens',8),
(150,'Mutual','Marcelo Garau',8)
